include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [lib/src/generated/**, lib/**/*.g.dart]
  errors:
    todo: ignore
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
