include: flutter_lints.yaml

analyzer:
  exclude:
    - lib/src/generated/platform_bindings.g.dart
  language:
    # Do not cast nullable values to non-nullable types.
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
